spring:
  application:
    name:
      realworld_backend
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: sa
    password: pass

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true

jwt:
  secretKey: secretKey
  accessTokenExpire: 86400
  refreshTokenExpire: 2592000