### All Articles
GET {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles by Author
GET {{host}}/articles?author={{author}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles Favorited by Username
GET {{host}}/articles?favorited={{favorited}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles by Tag
GET {{host}}/articles?tag={{tag}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Create Articles
POST {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "article": {
    "title": "{{article.title}}",
    "description": "{{article.description}}",
    "body": "{{article.body}}",
    "tagList": {{article.tagList}}
  }
}

### Update Article
PUT {{host}}/articles/{{slug}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "article": {
    "body": "With two hands"
  }
}

### Delete Article
DELETE {{host}}/articles/{{slug}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}