@host = http://localhost:8080
@author = test
@slug = slug
@username = username
@tag = tag
@commentId = commentId

### Create Articles
POST {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "Very carefully.",
    "tagList": [
      "training",
      "dragons"
    ]
  }
}

### Feed
GET {{host}}/articles/feed
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### All Articles
GET {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### All Articles with auth
GET {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Articles by Author
GET {{host}}/articles?author={{author}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Articles by Author with auth
GET {{host}}/articles?author={{author}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Single Article by slug
GET {{host}}/articles/{{slug}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Articles by Tag
GET {{host}}/articles?tag={{tag}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Update Article
PUT {{host}}/articles/{{slug}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "article": {
    "body": "With two hands"
  }
}

### Favorite Article
POST {{host}}/articles/{{slug}}//favorite
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Articles Favorited by Username
GET {{host}}/articles?favorited={{username}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Articles Favorited by Username with auth
GET {{host}}/articles?favorited={{username}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Unfavorite Article
DELETE {{host}}/articles/{{slug}}/favorite
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Create Comment for Article
POST {{host}}/articles/{{slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "comment": {
    "body": "Thank you so much!"
  }
}

### All Comments for Article
GET {{host}}/articles/{{slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### All Comment for Article without login
GET {{host}}/articles/{{slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Delete Comment for Article
DELETE {{host}}/articles/{{slug}}/comments/{{commentId}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Delete Article
DELETE {{host}}/articles/{{slug}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}