### All Articles
GET {{host}}/articles
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles by Author
GET {{host}}/articles?author={{author}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles Favorited by Username
GET {{host}}/articles?favorited={{favorited}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Articles by Tag
GET {{host}}/articles?tag={{tag}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest