### Register
POST {{host}}/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{register_user.email}}",
    "password": "{{register_user.password}}",
    "username": "{{register_user.username}}"
  }
}

### Login
POST {{host}}/users/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{user.email}}",
    "password": "{{user.password}}"
  }
}

### Login and Remeber Token
POST {{host}}/users/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{user.email}}",
    "password": "{{user.password}}"
  }
}

> {%
  client.log(response.body);
  client.log("token : " + response.body.user.token);
  client.global.set("auth_token", response.body.user.token);
%}

### Current User
GET {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Update User
PUT {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "user": {
    "email": "{{update_user.email}}",
    "username": "{{update_user.username}}",
    "password": "{{update_user.password}}",
    "image": "{{update_user.image}}",
    "bio": "{{update_user.bio}}"
  }
}