### Register
POST {{host}}/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{user.create.email}}",
    "password": "{{user.create.password}}",
    "username": "{{user.create.username}}"
  }
}

### Login
POST {{host}}/users/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{user.default.email}}",
    "password": "{{user.default.password}}"
  }
}

### Login and Remeber Token
POST {{host}}/users/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": "{{user.default.email}}",
    "password": "{{user.default.password}}"
  }
}

> {%
  client.log(response.body);
  client.log("token : " + response.body.user.token);
  client.global.set("auth_token", response.body.user.token);
%}

### Current User
GET {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Update User
PUT {{host}}/user
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "user": {
    "email": "{{user.update.email}}",
    "username": "{{user.update.username}}",
    "password": "{{user.update.password}}",
    "image": "{{user.update.image}}",
    "bio": "{{user.update.bio}}"
  }
}