### Create Comment for Article
POST {{host}}/articles/{{comment.slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "comment": {
    "body": "{{comment.body}}"
  }
}

> {%
  client.log(response.body);
  client.global.set("comment.commentId", response.body.comment.id);
%}

### All Comments for Article
GET {{host}}/articles/{{comment.slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### All Comment for Article without login
GET {{host}}/articles/{{comment.slug}}/comments
Content-Type: application/json
X-Requested-With: XMLHttpRequest

### Delete Comment for Article
DELETE {{host}}/articles/{{comment.slug}}/comments/{{comment.commentId}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}