### Profile
GET {{host}}/profiles/{{profile.default.username}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Follow Profile
POST {{host}}/profiles/{{profile.default.username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Unfollow Profile
DELETE {{host}}/profiles/{{profile.default.username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}
