### Register Celeb
POST {{host}}/users
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "user": {
    "email": {{user.email}},
    "password": {{user.password}},
    "username": {{user.username}}
  }
}

### Profile
GET {{host}}/profiles/celeb_{{user.username}}
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

### Follow Profile
POST {{host}}/profiles/celeb_{{user.username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}

{
  "user": {
    "email": {{user.email}}
  }
}

### Unfollow Profile
DELETE {{host}}/profiles/celeb_{{user.username}}/follow
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Token {{auth_token}}
